"""empty message

Revision ID: 4b8e0bdccafc
Revises: f78b51635964
Create Date: 2019-03-10 04:57:28.540395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b8e0bdccafc'
down_revision = 'f78b51635964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('email', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'user_profiles', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', type_='unique')
    op.drop_column('user_profiles', 'email')
    # ### end Alembic commands ###
